# Generated by Django 6.0.4 on 2026-04-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_category_course_created_at_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
